### ISSUE TITLE
Visitors have to log in to read the static pages

### ISSUE THREAD

**Issue by WikiRik** [csvalpha/amber-ui#285]
### How to reproduce
1. Go to csvalpha.nl and click on [Algemeen Bestuur](https://csvalpha.nl/static-pages/bestuur) (or other static pages, including the one linked from 'Lees meer over onze vereniging')

### Expected behaviour
You should be able to correctly open the page and see the information on that page.

### Current behaviour
You get redirected to the loginpage.

### Additional info
It might be related to #274 although I'm not sure how long this has been a bug.

**Comment by Matthijsy** [comment]
Thanks for alerting us about this Rik! The issue is that the `static-page.show` route has the authenticated route instead of the application route.

For the person fixing this, you should change this line: https://github.com/csvalpha/amber-ui/blob/staging/app/routes/static-pages/show.js#L3
Please also fix it for the `article.show` route, since that one has the same issue
