### ISSUE TITLE
Search doesn't work on page > 1

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-ui#29]
### How to reproduce
1. go to page 3
1. Search with results which are only on page 1

### Expected behaviour
the page is reset to 1 and you see results

### Current behaviour
You keep on the current page, so you do not see results which is confusing

*Optionally add some screenshots*

**Comment by Matthijsy** [comment]
It does work on /user, but doesn't on /polls

**Comment by FeijevanAbbema** [comment]
For now left for what it is. The reason why it doesn't work is because a queryparam with page x is send to the api. The api will return the same page x even if it is empty. So before you send an api request with a search queryparam you should first set the page queryparam to 1. This can't be done in a neat way
